### PR TITLE
Fix for footnote glyphs not appearing with row labels

### LINKED ISSUE #437: Adding footnote to cell stub does not work
Reference: https://github.com/rstudio/gt/blob/master/tests/gt-examples/01-html-script/html-13-adding_footnotes.R
If you try to add a footnote to a stub, glyph is not show in the particular row specified in `locations`

Below is a comprehensive example testing footnotes at several parts in a table. However, note the code snippet 
` 
tab_footnote(
    footnote = "A stub cell.",
    locations = cells_stub(rows = 1) 
  )
`

```r
library(gt)

# Create a table with footnotes in various cell types

# Input table
tbl <-
  dplyr::tribble(
    ~date,        ~rowname,  ~value_1,  ~value_2,
    "2018-02-10", "1",       20.4,      361.1,
    "2018-02-10", "2",       10.9,      743.3,
    "2018-02-10", "3",       34.6,      344.7,
    "2018-02-10", "4",        8.3,      342.3,
    "2018-02-11", "5",       28.3,      234.9,
    "2018-02-11", "6",       75.5,      190.9,
    "2018-02-11", "7",       63.1,        2.3,
    "2018-02-11", "8",       25.8,      184.3,
    "2018-02-11", "9",        5.2,      197.2,
    "2018-02-11", "10",      55.3,      284.6)

# Create a display table
footnotes_tbl <-
  gt(data = tbl, groupname_col = "date") %>%
  tab_spanner(
    label = "values",
    columns = starts_with("value")
  ) %>%
  tab_footnote(
    footnote = "This is an even smaller number.",
    locations = cells_data(columns = vars(value_1), rows = 9)
  ) %>%
  tab_footnote(
    footnote = "This is a small number.",
    locations = cells_data(columns = vars(value_1), rows = 4)
  ) %>%
  tab_footnote(
    footnote = "First data cell.",
    locations = cells_data(columns = "value_1", rows = 1)
  ) %>%
  tab_footnote(
    footnote = "The first row group",
    locations = cells_group(groups = ends_with("10"))
  ) %>%
  tab_footnote(
    footnote = "Two sets of values",
    locations = cells_column_spanners(spanners = starts_with("val"))
  ) %>%
  tab_footnote(
    footnote = "A stub cell.",
    locations = cells_stub(rows = 1) 
  ) %>%
  tab_style(
     style = cell_fill(),
    locations = cells_stub(rows = 1)
  )%>%
  tab_footnote(
    footnote = md("`value_1` is the first column of values."),
    locations = cells_column_labels(columns = vars(value_1))
  )

footnotes_tbl

```

Attaching the snapshot of the gt table produced where the footnote is not shown in the cell stub row 1.
html_13_footnote_issue

### LINKED ISSUE #443: Adding a footnote to a cell stub sometimes results in error (different from issue #437)
I'm trying to add a footnote to a cell stub in a table built with ```gt``` by ```modelsummary```, but when the package tries to render the table, I get an error.

Here is a simple, reproducible example:
```r
library(MASS)
library(modelsummary)
library(gt)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

model <- lm(Literacy ~ Crime_prop + Infants, dat)

gt <- msummary(model) %>% 
  tab_footnote(                                                                                                                                                                               
    footnote = "This is a footnote.",                                                                                           
    locations = cells_stub(rows = vars(Infants))
  )

gt
```

The error I get when I try to run this script is: ```Can't find column NA in `.data`.```

When I run ```rlang::last_error()```, here is what I get:
```
Can't find column NA in `.data`.
Backtrace:
  1. base::source(...)
  3. gt:::print.gt_tbl(yy$value)
  4. gt:::as.tags.gt_tbl(x, ...)
  5. gt:::render_as_html(data = x)
  6. gt:::build_data(., context = "html")
 14. gt:::apply_footnotes_to_output(data = data, context = context)
 15. tibble:::`[.tbl_df`(body, footnotes_data_marks$rownum[i], footnotes_data_marks$colname[i])
 17. tibble:::check_names_df(j, x)
 18. tibble:::check_names_before_after_character(j, names(unclass(x)))
 19. base::source(...)
```

So the error seems to be occurring in ```apply_footnotes_to_output```, but of course the source of the error may be elsewhere, perhaps in ```build_data```.

Note that, when I try with other types of footnotes, it works fine:
```
library(MASS)
library(modelsummary)
library(gt)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

model <- lm(Literacy ~ Crime_prop + Infants, dat)

gt <- msummary(model) %>% 
  tab_footnote(                                                                                                                                                                                  
    footnote = "Here is a footnote",                        
    locations = cells_column_labels(columns = vars(`Model 1`))
  ) %>%                                                                                                                                  
  tab_footnote(                                                                                                                      
    footnote = "Here is another footnote",
    locations = cells_data(columns = vars(`Model 1`), rows = vars(Infants))
  )

gt
```

This issue may be related to #437, but it's distinct, since in the case I'm talking about it's not just that the glyph doesn't appear in the cell stub, but trying to render the table results in an outright error. I was able to reproduce #437 and there was no error:
```
library(gt)

# Create a display table where individual table cells are styled

# Input table
library(gt)

# Create a display table where individual table cells are styled

# Input table
tbl <-
  dplyr::tribble(
    ~rowname, ~value,  ~value_2,
    "1",      361.1,   260.1,
    "2",      184.3,   84.4,
    "3",      342.3,   126.3,
    "4",      234.9,   37.1,
    "5",      190.9,   832.5,
    "6",      743.3,   281.2,
    "7",      252.3,   732.5,
    "8",      344.7,   281.2)

# Create a display table
gt <- gt(tbl, rowname_col = "rowname") %>%
  tab_footnote(                                                                                                                                                                               
    footnote = "This is a footnote.",                                                                                           
    locations = cells_stub(rows = c(1))
  )

gt
```

Here is the output: 
Rplot

### PR DESCRIPTION
**Pull request by rich-iannone**
This PR fixes an issue where footnote glyphs would not appear in any cells located in the stub. The underlying problem is in the `output_df_row_as_vec()` util function, which doesn't obtain the rendered value for the stub cell (which includes footnote text).

Further issues stem from the fact that the columns associated with the row labels or group labels are not well-defined in the gt object. This PR should fix that. The current state of the `dt_boxhead_init()` function shows that several `type` values for columns are not yet implemented; only `default` and `hidden` are used, but `stub` and `row_group` would be helpful to precisely identify those columns at a later time.

Fixes #437 
Fixes #443

### CODE REVIEW

File: R/dt_boxhead.R [hunk 1]
```diff
@@ -75,7 +75,22 @@ dt_boxhead_set_hidden <- function(data, vars) {
   dt_boxhead <- dt_boxhead_get(data = data)
 
   dt_boxhead[which(dt_boxhead$var %in% vars), "type"] <- "hidden"
+  dt_boxhead %>% dt_boxhead_set(data = data)
+}
+
+dt_boxhead_set_stub <- function(data, vars) {
```
Comment (jcheng5) [inline R/dt_boxhead.R]: `vars` should be `var` and assumed to be length 1

File: R/dt_boxhead.R [hunk 2]
```diff
@@ -75,7 +75,22 @@ dt_boxhead_set_hidden <- function(data, vars) {
...
+
+  dt_boxhead <- dt_boxhead_get(data = data)
 
+  dt_boxhead[which(dt_boxhead$var %in% vars), "type"] <- "stub"
+  dt_boxhead %>% dt_boxhead_set(data = data)
+}
+
+dt_boxhead_set_row_group <- function(data, vars) {
```
Comment (jcheng5) [inline R/dt_boxhead.R]: `vars` should be `var` and assumed to be length 1

File: R/dt_boxhead.R [hunk 3]
```diff
@@ -70,14 +70,61 @@ dt_boxhead_edit <- function(data, var, ...) {
...
+  } else {
+    stop("The `add_where` value must be either `top` or `bottom`.")
+  }
+
+  dt_boxhead %>% dt_boxhead_set(data = data)
+}
+
 dt_boxhead_set_hidden <- function(data, vars) {
 
   dt_boxhead <- dt_boxhead_get(data = data)
```
Comment (jcheng5) [inline R/dt_boxhead.R]: I won't make you change it now, but it would be nice for functions like this to throw an error unless `all(vars %in% dt_boxhead$var)`

File: R/dt_data.R [hunk 4]
```diff
@@ -10,7 +10,33 @@ dt_data_set <- function(data, data_tbl) {
...
-dt_data_init <- function(data, data_tbl = NULL) {
+# rownames_to_column is a string; if not NA, it means the row.names(data_tbl)
+# should be turned into a column with the name !!rownames_to_column
+dt_data_init <- function(data, data_tbl, rownames_to_column = NA) {
 
-  dt_data_set(data, data_tbl)
+  # If the option to place rownames in the stub
+  # is taken, then the `stub_df` data frame will
+  # be pre-populated with rownames in the `rowname`
+  # column; otherwise, this will be an empty df
```
Comment (jcheng5) [inline R/dt_data.R]: This comment is wrong now

File: R/dt_data.R [hunk 5]
```diff
@@ -10,7 +10,33 @@ dt_data_set <- function(data, data_tbl) {
...
+  if (!is.na(rownames_to_column)) {
+
+    data_rownames <- rownames(data_tbl)
+
+    # In the rare instance there is a column named
+    # `rowname` modify the name slightly and provide
+    # a warning about the change
```
Comment (jcheng5) [inline R/dt_data.R]: This comment is also wrong now

File: R/gt.R [hunk 6]
```diff
@@ -83,17 +87,30 @@ gt <- function(data,
                id = random_id(),
                row_group.sep = getOption("gt.row_group.sep", " - ")) {
 
+  if (inherits(data, "grouped_df")) {
```
Comment (jcheng5) [inline R/gt.R]: What happens if a data frame is grouped, and also has `groupname_col`? What I'm seeing is that the `grouped_df` aspect wins.

```
mtcars %>% group_by(vs) %>% gt(groupname_col = "cyl")
```

Comment (jcheng5) [reply R/gt.R]: You could solve this by having `groupname_col` default to `dplyr::group_vars(data)`, perhaps?

File: R/summary_rows.R [hunk 7]
```diff
@@ -115,6 +115,24 @@ summary_rows <- function(data,
...
+        column_width = list(NULL),
+        hidden_px = list(NULL),
+        add_where = "top"
+      )
+
+    # Add the `"rowname"` column into `_data`
+    data$`_data` <-
+      data$`_data` %>%
+      dplyr::mutate(rowname = rep("", nrow(data$`_data`))) %>%
+      dplyr::select(rowname, dplyr::everything())
```
Comment (jcheng5) [inline R/summary_rows.R]: This can't possibly be right, can it? Don't you need to look in `_boxh` to see if a stub column already exists?

Comment (jcheng5) [reply R/summary_rows.R]: This doesn't work, should it?

```
mtcars %>%
  gt(rownames_to_stub = TRUE) %>%
  summary_rows(fns = list(mean = ~mean(.)))
```

File: R/utils_render_footnotes.R [hunk 8]
```diff
@@ -552,10 +552,12 @@ apply_footnotes_to_output <- function(data,
   if (nrow(footnotes_tbl_data) > 0) {
 
     if ("stub" %in% footnotes_tbl_data$locname &&
-        "rowname" %in% colnames(body)) {
+        !is.na(dt_boxhead_get_var_stub(data))) {
```
Comment (jcheng5) [inline R/utils_render_footnotes.R]: It feels like if `"stub" %in% footnotes_tbl_data$locname`, and `is.na(dt_boxhead_get_var_stub(data))`, that should be an error. In fact, that should probably be an error at the time the footnote is added.

File: R/utils_render_footnotes.R [hunk 9]
```diff
@@ -552,10 +552,12 @@ apply_footnotes_to_output <- function(data,
...
+
+      boxhead_var_stub <- dt_boxhead_get_var_stub(data)
 
       footnotes_tbl_data[
-        which(is.na(footnotes_tbl_data$colname)), "colname"] <- "rowname"
+        which(is.na(footnotes_tbl_data$colname)), "colname"] <- boxhead_var_stub
```
Comment (jcheng5) [inline R/utils_render_footnotes.R]: Would `which(is.na(footnotes_tbl_data$colname))` be better as `footnotes_tbl_data$locname == "stub"`?

File: R/summary_rows.R (hunk 7 above)
Comment (jcheng5) [reply R/summary_rows.R]: We're good!

**Comment by rich-iannone** [comment]
Thanks for all the help with this one. I did quite a bit of manual testing, just to make sure everything is good (and it is). Will merge.
